package io.rsi.codespace.util;

public class Main {
    public static void main(String[] args) {
        StringBuilder query = new StringBuilder();
        query.append("WITH CONTACT_LIST AS ");
        query.append("  (SELECT PTR_CONT_ROWID ");
        query.append("  FROM C_PTR_CONT K ");
        query.append("  WHERE ( ");
        query.append("    CASE ");
        query.append("      WHEN K.PRMRY_EMAIL      IS NOT NULL ");
        query.append("      AND (:IN_PRIMARY_EMAIL) IS NOT NULL ");
        query.append("      AND LOWER(K.PRMRY_EMAIL)        = LOWER(:IN_PRIMARY_EMAIL) ");
        query.append("      THEN 1 ");
        query.append("      WHEN ( ");
        query.append("      LOWER(NVL2(K.FRST_NM,K.FRST_NM,'XX'))               = LOWER(NVL2((:IN_FIRST_NAME),(:IN_FIRST_NAME),NVL(K.FRST_NM,'XX'))) ");
        query.append("      AND ");
        query.append("      LOWER(NVL2(K.LST_NM,K.LST_NM,'XX'))                 = LOWER(NVL2((:IN_LAST_NAME),(:IN_LAST_NAME),NVL(K.LST_NM,'XX'))) ");
        query.append("      AND ");
        query.append("      LOWER(NVL2(K.SCDRY_EMAIL,K.SCDRY_EMAIL,'XX'))       = LOWER(NVL2((:IN_SECONDARY_EMAIL),(:IN_SECONDARY_EMAIL),NVL(K.SCDRY_EMAIL,'XX'))) ");
        query.append("      AND ");
        query.append("      LOWER(NVL2(K.PH_NUM,K.PH_NUM,'XX'))                 = LOWER(NVL2((:IN_PHONE_NUMBER),(:IN_PHONE_NUMBER),NVL(K.PH_NUM,'XX'))) ");
        query.append("      AND ");
        query.append("      LOWER(NVL2(K.MOB_NUM,K.MOB_NUM,'XX'))               = LOWER(NVL2((:IN_MOBILE_NUMBER),(:IN_MOBILE_NUMBER),NVL(K.MOB_NUM,'XX'))) ");
        query.append("      AND (:IN_PRIMARY_EMAIL)                   IS NULL ");
        query.append("      AND LOWER(NVL(K.FRST_NM ");
        query.append("        || K.LST_NM ");
        query.append("        || K.SCDRY_EMAIL ");
        query.append("        || K.PH_NUM ");
        query.append("        || K.MOB_NUM, 'XX')) <> 'XX' ) ");
        query.append("      THEN 1 ");
        query.append("      ELSE 0 ");
        query.append("    END ) = 1 ");
        query.append("  ) , ");
        query.append("  CONTACT_IDENTIFIER_INFO AS ");
        query.append("  (SELECT * ");
        query.append("  FROM ");
        query.append("    (SELECT PTR_ROWID CONTACT_MDM_ID, ");
        query.append("      TYP_TYPE_CD, ");
        query.append("      CODE ");
        query.append("    FROM C_PTR_ALT_CODES ");
        query.append("    WHERE TYP_TYPE_CD IN ('PTR_ALT_CODES.CNTSCV','PTR_ALT_CODES.CNTFCT') ");
        query.append("    AND EXISTS ");
        query.append("      (SELECT 1 ");
        query.append("      FROM CONTACT_LIST KK ");
        query.append("      WHERE C_PTR_ALT_CODES.PTR_ROWID = KK.PTR_CONT_ROWID ");
        query.append("      ) ");
        query.append("    ) PIVOT (MIN(CODE) FOR (TYP_TYPE_CD) IN ( 'PTR_ALT_CODES.CNTSCV' AS CONT_SCV_CODE, 'PTR_ALT_CODES.CNTFCT' AS CONT_FACT_CODE)) ");
        query.append("  ), ");
        query.append("  CUSTOMER_IDENTIFIER_INFO AS ");
        query.append("  (SELECT * ");
        query.append("  FROM ");
        query.append("    (SELECT PTR_ROWID CUSTOMER_MDM_ID, ");
        query.append("      TYP_TYPE_CD, ");
        query.append("      CODE ");
        query.append("    FROM C_PTR_ALT_CODES ");
        query.append("    WHERE HUB_STATE_IND = 1 ");
        query.append("    AND TYP_TYPE_CD    IN ('PTR_ALT_CODES.CSTSCV','PTR_ALT_CODES.CSTFCT') ");
        query.append("    AND EXISTS ");
        query.append("      (SELECT 1 ");
        query.append("      FROM CONTACT_LIST ");
        query.append("      INNER JOIN C_PTR_REL ");
        query.append("      ON C_PTR_REL.CHLD_RL_ROWID      = CONTACT_LIST.PTR_CONT_ROWID ");
        query.append("      WHERE C_PTR_ALT_CODES.PTR_ROWID = C_PTR_REL.PRNT_RL_ROWID ");
        query.append("      ) ");
        query.append("    ) PIVOT (MIN(CODE) FOR (TYP_TYPE_CD) IN ( 'PTR_ALT_CODES.CSTSCV' AS CUST_SCV_CODE, 'PTR_ALT_CODES.CSTFCT' AS CUST_FACT_CODE)) ");
        query.append("  ) ");
        query.append(" ");
        query.append(" ");
        query.append(" ");
        query.append("SELECT * ");
        query.append("FROM ");
        query.append("  (SELECT SUBSTR(CONT_FACT_CODE,1,2) COUNTRY_NM, ");
        query.append("    CUSTOMER_IDENTIFIER_INFO.CUST_SCV_CODE CUSTOMER_SCV_CODE, ");
        query.append("    CUSTOMER_IDENTIFIER_INFO.CUST_FACT_CODE CUSTOMER_CODE, ");
        query.append("    C_PTR_REL.PARTY_RL_REL_TYP_CD, ");
        query.append("    CONTACT_IDENTIFIER_INFO.CONTACT_MDM_ID ROWID_OBJECT, ");
        query.append("    C_PTR_PARTY_RL.HUB_STATE_IND, ");
        query.append("    C_PTR_PARTY_RL.IS_ACTV_IND CONTACT_STATUS, ");
        query.append("    CONT_FACT_CODE CONTACT_CODE, ");
        query.append("    CONT_SCV_CODE CONTACT_SCV_CODE, ");
        query.append("    C_PTR_CONT.FRST_NM FIRST_NAME, ");
        query.append("    C_PTR_CONT.LST_NM LAST_NAME, ");
        query.append("    C_PTR_REL.PARTY_RL_REL_TYP_CD CONTACT_ROLE, ");
        query.append("    C_PTR_CONT.EXTN EXTN, ");
        query.append("    C_PTR_CONT.PH_NUM PH_NUM, ");
        query.append("    PH_NUM_CD.DIALNG_CD PH_NUM_DIALING_CD, ");
        query.append("    PH_NUM_CD.DAILNG_CD_DESC PH_NUM_DIALING_CD_DESC, ");
        query.append("    C_PTR_CONT.MOB_NUM MOB_NUM, ");
        query.append("    MOB_NUM_CD.DIALNG_CD MOB_NUM_DIALING_CD, ");
        query.append("    MOB_NUM_CD.DAILNG_CD_DESC MOB_NUM_DIALING_CD_DESC, ");
        query.append("    C_PTR_CONT.FAX FAX, ");
        query.append("    FAX_NUM_CD.DIALNG_CD FAX_NUM_DIALING_CD, ");
        query.append("    FAX_NUM_CD.DAILNG_CD_DESC FAX_NUM_DIALING_CD_DESC, ");
        query.append("    C_PTR_CONT.PRMRY_EMAIL PRMRY_EMAIL, ");
        query.append("    C_PTR_CONT.SCDRY_EMAIL SCDRY_EMAIL, ");
        query.append("    C_PTR_CONT.GRP_CONT_IND GRP_CONT_IND ");
        query.append("  FROM CONTACT_IDENTIFIER_INFO ");
        query.append("  INNER JOIN C_PTR_CONT ");
        query.append("  ON C_PTR_CONT.PTR_CONT_ROWID = CONTACT_IDENTIFIER_INFO.CONTACT_MDM_ID ");
        query.append("  INNER JOIN C_PTR_REL ");
        query.append("  ON C_PTR_REL.CHLD_RL_ROWID = C_PTR_CONT.PTR_CONT_ROWID ");
        query.append("  INNER JOIN CUSTOMER_IDENTIFIER_INFO ");
        query.append("  ON CUSTOMER_IDENTIFIER_INFO.CUSTOMER_MDM_ID = C_PTR_REL.PRNT_RL_ROWID ");
        query.append("  INNER JOIN C_PTR_PARTY_RL ");
        query.append("  ON C_PTR_PARTY_RL.ROWID_OBJECT = CONTACT_IDENTIFIER_INFO.CONTACT_MDM_ID ");
        query.append("  LEFT OUTER JOIN C_CTM_INTL_DIALNG_CD PH_NUM_CD ");
        query.append("  ON PH_NUM_CD.ROWID_OBJECT = C_PTR_CONT.INTL_DIALNG_ROWID_PH ");
        query.append("  LEFT OUTER JOIN C_CTM_INTL_DIALNG_CD MOB_NUM_CD ");
        query.append("  ON MOB_NUM_CD.ROWID_OBJECT = C_PTR_CONT.INTL_DIALNG_ROWID_MOB ");
        query.append("  LEFT OUTER JOIN C_CTM_INTL_DIALNG_CD FAX_NUM_CD ");
        query.append("  ON FAX_NUM_CD.ROWID_OBJECT = C_PTR_CONT.INTL_DIALNG_ROWID_FAX ");
        query.append("  )K ");
        query.append("WHERE (K.CONTACT_CODE NOT IN (:IN_CONTACT_CODE) OR (:IN_CONTACT_CODE)     IS NULL )");
        query.append(" AND (K.PARTY_RL_REL_TYP_CD IN ('CUST_CONT')) ");

        System.out.println(query.toString());
    }
}
